services:
  - type: static_site
    name: form-validation
    env: static
    repo: https://github.com/khadimflash/Form_Validation.git # optional
    branch: main
    buildFilter:
      paths:
      - "**/*.html"
      - "**/*.js"
      - "**/*.css"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
